/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author aakash
 */
public class Index extends javax.swing.JFrame {

    String user = null;
    /**
     * Creates new form Index
     * @param usr
     */
    public Index(String usr) {
        initComponents();
        user = usr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Predict_Label = new javax.swing.JLabel();
        Forum_Label = new javax.swing.JLabel();
        FirstAid_Label = new javax.swing.JLabel();
        LogOut_Label = new javax.swing.JLabel();
        Helpline_Label = new javax.swing.JLabel();
        Img_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Predict_Label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Predict_Label.setForeground(new java.awt.Color(0, 62, 255));
        Predict_Label.setText("     PREDICT");
        Predict_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Predict_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Predict_LabelMousePressed(evt);
            }
        });
        getContentPane().add(Predict_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 50));

        Forum_Label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Forum_Label.setForeground(new java.awt.Color(0, 62, 255));
        Forum_Label.setText("       FORUM");
        Forum_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forum_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Forum_LabelMousePressed(evt);
            }
        });
        getContentPane().add(Forum_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 110, 50));

        FirstAid_Label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        FirstAid_Label.setForeground(new java.awt.Color(0, 62, 255));
        FirstAid_Label.setText("    FIRST AID");
        FirstAid_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FirstAid_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FirstAid_LabelMousePressed(evt);
            }
        });
        getContentPane().add(FirstAid_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 100, 50));

        LogOut_Label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LogOut_Label.setForeground(new java.awt.Color(0, 62, 255));
        LogOut_Label.setText("  LOG OUT");
        LogOut_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogOut_LabelMousePressed(evt);
            }
        });
        getContentPane().add(LogOut_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 80, 40));

        Helpline_Label.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Helpline_Label.setForeground(new java.awt.Color(0, 62, 255));
        Helpline_Label.setText("  HELPLINE");
        Helpline_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Helpline_LabelMousePressed(evt);
            }
        });
        getContentPane().add(Helpline_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 100, 50));

        Img_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/healthcare-1.jpg"))); // NOI18N
        getContentPane().add(Img_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Predict_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Predict_LabelMousePressed
        Prediction p = new Prediction();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Predict_LabelMousePressed

    private void Forum_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Forum_LabelMousePressed
        Forum f = new Forum(user);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Forum_LabelMousePressed

    private void FirstAid_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstAid_LabelMousePressed
        FirstAid1 fa = new FirstAid1(user);
        fa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FirstAid_LabelMousePressed

    private void LogOut_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_LabelMousePressed
        MainPage mp = new MainPage();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOut_LabelMousePressed

    private void Helpline_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Helpline_LabelMousePressed
        Emergency e = new Emergency();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Helpline_LabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstAid_Label;
    private javax.swing.JLabel Forum_Label;
    private javax.swing.JLabel Helpline_Label;
    private javax.swing.JLabel Img_Label;
    private javax.swing.JLabel LogOut_Label;
    private javax.swing.JLabel Predict_Label;
    // End of variables declaration//GEN-END:variables
}
